### ISSUE TITLE
Enable integration with model hosting

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/leapfrogai#103]
There are popular model hosting platforms, e.g. Huggingface.  Enabling the creation of a Leapfrog Model package from the name of a hugging face model would significantly enable the bredth of models that we could provide to end users

zarf-config.yaml
```yaml
create:
  set:
    model_hosting: huggingface
    model_name: TheBloke/starcoder-GGML
    model_type: llama.cpp
```
```[tasklist]
### Tasks
```
