### ISSUE TITLE
[BUG] -- Domain Prefixed with Leafrogai 2x

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns/leapfrogai#181]
## Issue
When deploying a generated zarf package from the leapfrogai repo, the host for the VirtualService ends up being `leapfrogai.leapfrogai.bigbang.dev`, which causes an SSL  error because the cert for DUBBD only allows for `*.bibang.dev`.

## Proposed Solutions
Remove the `leapfrogai` from the domain in zarf-config.yaml

```
deploy:
    set:
      domain: leapfrogai.bigbang.dev
      whisper_enabled: "true"
```

becomes

```
deploy:
    set:
      domain: bigbang.dev
      whisper_enabled: "true"
```
(this would match what the chart and values.yaml are already doing)

or remove it from the vs.yaml in /chart /templates

```
hosts:
  - leapfrogai.{{ .Values.domain }}
```
becomes
```
hosts:
  - {{ .Values.domain }}
```
