### ISSUE TITLE
Unify config interface

### ISSUE THREAD

**Issue by gerred** [defenseunicorns/leapfrogai#229]
Given we're moving to generic backends, we've been taking stabs at configuration, starting with ctransformers and vllm. Other backends (ctranslate2, etc) will presumably need this as well.

We're stabbing at a format like:

```yaml
name: "mpt-7b-8k-chat"
model_type: "mpt"
trust_remote_code: true # defaults to false
model_context_length: 8192
prompt_formats:
  chat:
    system: "<|im_start|>system\n{}<|im_end|>\n"
    assistant: "<|im_start|>assistant\n{}<|im_end|>\n"
    user: "<|im_start|>user\n{}<|im_end|>\n"
defaults:
  temperature: 0.5
```

to get started. This isn't necessarily exhaustive at the moment. We should move this config object up into the leapfrogai pypi package, as well as the config loading, to make it an appliance common across model backends.
