### ISSUE TITLE
chore: burndown remaining dockerfile lint issues

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai#984]
### Describe what should be investigated or refactored

The Dockerfile lint is still bringing up several warnings and errors throughout our manifests that may be good to fix in the future:

```yaml
failure-threshold: error
# TODO: slowly burn down these lower priority container issues
ignored:
  - DL3007 # use of latest image
  - DL3042 # pip --no-cache-dir
  - DL4006 # shell usage warning
  - DL3009 # apt-get list
  - DL3015 # --no-install-recommends
  - DL3018 # pinning distro package versions
  - DL3008 # pinning distro package versions
  - DL3045 # usage of relative COPY
  - DL3002 # last user as root
  - SC2086 # double quote vs single quote usage
```

### Links to any relevant code

- https://github.com/defenseunicorns/leapfrogai/blob/main/.hadolint.yaml

### Additional context

Testing and some investigation will be required to ensure these changes do not break existing functionality.
