### ISSUE TITLE
chore: timeout for all e2e tests

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai#991]
### Describe what should be investigated or refactored

There are cases where the E2E tests, due to hanging K8s cluster deployments and testing, will not timeout even after several hours, causing billed time to be high when a pipeline is not monitored closely or during cron-job triggered jobs (e.g., nightly, snapshots, or weekly, etc.).

Most tests should finish within 1 hour (conservative, more like 45 minutes), and as such, should be provided a timeout at the workflow level like that; whereas each job and/or step will require some investigation.

### Links to any relevant code

Examples of each type are described below.

#### Jobs:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # The job will timeout after 30 minutes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
```

This job will be automatically cancelled if it exceeds 30 minutes.

#### Workflow:

```yaml
name: CI

on:
  push:
    branches:
      - main

timeout-minutes: 60  # The entire workflow will timeout after 60 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
```

### Additional context

Example of a hanging pipeline with no timeout: https://github.com/defenseunicorns/leapfrogai/actions/runs/10728757617/job/29753991319?pr=937
